# Generated by Django 4.0.4 on 2022-05-14 19:57

import datetime
import django.core.validators
from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Last Name')),
                ('age', models.PositiveSmallIntegerField()),
                ('birthday', models.DateField(default=datetime.date.today, validators=[students.validators.AdultValidator(20)])),
                ('phone_number', models.CharField(max_length=20, null=True, validators=[students.validators.phone_number_validator, django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
        ),
    ]
