# Generated by Django 4.0.4 on 2022-05-14 01:11

import django.core.validators
from django.db import migrations, models
import teachers.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Last Name')),
                ('discipline', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('phone_number', models.CharField(max_length=20, null=True, validators=[teachers.validators.phone_number_validator, django.core.validators.MinLengthValidator(3)])),
            ],
        ),
    ]
