# Generated by Django 4.0.4 on 2022-05-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('max_capacity', models.PositiveIntegerField()),
                ('curr_students', models.PositiveIntegerField()),
                ('disciplines', models.TextField()),
            ],
        ),
    ]
